/**
 * Mogador Chess Club — self-hosted web fonts.
 *
 *   node scripts/build-fonts.mjs
 *
 * Copies the woff2 subsets we actually use out of the fontsource packages into
 * public/fonts/, and generates src/styles/fonts.css with matching @font-face
 * rules. Outputs are committed, so a clean `npm ci && npm run build` needs
 * nothing from this script.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * WHY NOT JUST `@import '@fontsource-variable/inter/index.css'`?
 *
 * Two reasons, one fatal and one merely wasteful.
 *
 * FATAL: Vite resolves CSS `@import` before it rewrites `url()` references, and
 * for CSS pulled out of a package it does not rebase those URLs. The build
 * emits the @font-face rules pointing at `./files/inter-latin-wght-normal.woff2`
 * relative to `/_astro/`, copies no woff2 into dist, and warns rather than
 * fails. The site then silently falls back to Georgia and system-ui — the
 * typography is simply gone, and nothing is red. (Same family of problem as the
 * `tailwindcss/index.css` specifier note in global.css.)
 *
 * WASTEFUL: index.css declares every subset the family ships — Inter alone
 * carries cyrillic, cyrillic-ext, greek, greek-ext and vietnamese. A FR/EN site
 * never requests them, but they would land in dist/ and get swept into the
 * service-worker PRECACHE, which is not lazy: every first visit on Essaouira
 * mobile data would pay for Greek Inter up front.
 *
 * So: an explicit subset list, absolute /fonts/ URLs, and four files.
 * ─────────────────────────────────────────────────────────────────────────
 */

import { copyFileSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const OUT_DIR = fileURLToPath(new URL('../public/fonts/', import.meta.url));
const CSS_OUT = fileURLToPath(new URL('../src/styles/fonts.css', import.meta.url));

/**
 * FR and EN need `latin` and `latin-ext` and nothing else. `latin` already
 * covers the accented French vowels, the cedilla and the œ ligature; `latin-ext`
 * is kept for stray proper nouns (a player's surname, a Moroccan place name).
 */
const SUBSETS = ['latin', 'latin-ext'];

const FAMILIES = [
  { pkg: '@fontsource-variable/fraunces', family: 'Fraunces Variable', file: 'fraunces' },
  { pkg: '@fontsource-variable/inter', family: 'Inter Variable', file: 'inter' },
];

mkdirSync(OUT_DIR, { recursive: true });

const blocks = [
  '/* GENERATED by scripts/build-fonts.mjs — do not edit by hand.',
  ' * Re-run that script after changing the family or subset list; it explains',
  ' * why the fonts are copied into public/ instead of imported from the package.',
  ' */',
  '',
];

for (const { pkg, family, file } of FAMILIES) {
  // require.resolve returns a filesystem path; on Windows that is not a valid
  // URL base, so it goes through pathToFileURL before the directory is taken.
  const pkgDir = fileURLToPath(new URL('.', pathToFileURL(require.resolve(`${pkg}/package.json`))));
  const unicode = JSON.parse(readFileSync(`${pkgDir}unicode.json`, 'utf8'));

  for (const subset of SUBSETS) {
    const range = unicode[subset];
    if (!range) throw new Error(`${pkg} has no "${subset}" subset`);

    const name = `${file}-${subset}-wght-normal.woff2`;
    copyFileSync(`${pkgDir}files/${name}`, `${OUT_DIR}${name}`);
    console.log(`  public/fonts/${name}`);

    blocks.push(
      `/* ${family} — ${subset} */`,
      '@font-face {',
      `  font-family: '${family}';`,
      '  font-style: normal;',
      // The variable weight axis, exposed as a range so any weight interpolates
      // from the single file instead of pulling a second one.
      '  font-weight: 100 900;',
      // swap, not block: a lesson must be readable before the serif arrives.
      '  font-display: swap;',
      `  src: url('/fonts/${name}') format('woff2-variations');`,
      `  unicode-range: ${range};`,
      '}',
      '',
    );
  }
}

writeFileSync(CSS_OUT, blocks.join('\n'));
console.log('\n  src/styles/fonts.css\n');
